### ISSUE TITLE
TDD with AggregateRoots

### ISSUE THREAD

**Issue by devmsh** [spatie/laravel-event-sourcing#55]
I tried to read the documentation and see the example projects, but I did not figure out the best approach to develop an AggregateRoots in TDD.

I have several issues, maybe many of them not related to the package directly but I think it worth to be discussed here:

In the example project, you use primitive types as an AggregateRoot function params like `$amount`, or `$name` but for more complex examples the event may need 5+ pieces of information to be passed from the controller or the client-side.

When we write the tests, we use Model Factories to easily initiate a model data, how can we benefit from the same concept to generate the payloads of the events.

In addition to that, I did not figure out how can I make some assertion about the AggregateRoot internal functions like:

` $this->assertEquals(1000,$root->initial_balance)`  after a `root = WalletAggregateRoot::fake()...`. When I `dd` the `root` it seems that the aggregate root is these but private so we cannot access it or make any assertion?

Also, how can I test actions that need two aggregates collaboration? for example, in the larabank if I need to transfer amount between account to account, the transfer command will lead to invoke the deposit and withdraw from two different aggregate, and these internal events will not appear in the current testing mechanism.

I think these issues can be solved if you provide a solid test suite for the larabank example especially if you add an event that includes 5+ element on it to make the example more real world.

If any of the issues above not clear, I can provide you with some code snippets. 👍

**Comment by dilab** [comment]
My two cents:

1. `When I dd the root it seems that the aggregate root is these but private so we cannot access it or make any assertion?` 
You can always expose what is required, in your example, `AR:getInitialBalance`, so that you can go on with your unit test.

2. `Also, how can I test actions that need two aggregates collaboration?` When two AR need to communicate with each other, we can use [Saga events](https://microservices.io/patterns/data/saga.html). This way, you are able to decouple two ARs.
